cdif_columns_dict = {
    "1. Partners": [
        "Partner Name",
        "Partner External ID",
        "Partner Type",
        "Partner Approval Status",
        "Category",
        "Partner Head Quarters Address",
        "Partner Contact- Name",
        "Partner Contact-  Email",
        "Partner Contact-Work Phone",
        "Partner Contact- Title",
        "Supply Chain Mapping Required",
        "BCP Required",
        "Conflict Minerals Required",
        "Corporate Social Responsibility Required",
        "Capacity Risk Survey Required",
        "Change Notification Required",
        "Financial Risk 1: Credit Risk Score",
        "Financial Risk 2: Health Risk Score",
        "Financial Risk 3: Debt Rating Score",
        "Financial Risk 4:  Z Risk Score",
        "Partner Custom Defined Risk Score (1)",
        "Partner Custom Defined Risk Score (2)",
        "Partner Custom Defined Risk Score (3)",
        "Partner Custom Defined Risk Score (4)",
        "Partner Custom Defined Risk Score (5)",
        "Name of Escalation Manager (1)",
        "Name of Escalation Manager (2)",
        "Name of Escalation Manager (3)",
        "Partner Emergency Contact- Name",
        "Partner Emergency Contact- Email",
        "Partner Emergency Contact- Work Phone",
        "Partner DUNS Number",
        "Tier Level",
        "Higher Tier Partner",
    ],
    "2. Part sourcing": [
        "Part #",
        "Description",
        "Type",
        "Part Category",
        "Partner Name",
        "Partner Part #",
        "Qualification Status",
        "Alternate MPN #1",
        "Alternate MPN #2",
        "Alternate MPN #3",
        "Alternate MPN #4",
        "Alternate MPN #5",
        "Sourcing",
        "Split",
        "Part Custom Defined Risk Score (1)",
        "Part Custom Defined Risk Score (2)",
        "Part Custom Defined Risk Score (3)",
        "Part Custom Defined Risk Score (4)",
        "Part Custom Defined Risk Score (5)",
        "Supply Chain Mapping Required",
        "Conflict Minerals Required",
        "Change Notification Required",
        "Annual Spend on Partner Part",
    ],
    "3. BOM and Alt Parts": ["Product name", "Part #", "Alternate Part #"],
    "4. Product": [
        "Product Hierarchy Level 1",
        "Product Hierarchy Level 2",
        "Product Hierarchy Level 3",
        "Product Hierarchy Level 4",
        "Product Hierarchy Level 5",
        "Product Hierarchy Level 6",
        "Product Name",
        "Product Description",
        "Revenue Q1",
        "Revenue Q2",
        "Revenue Q3",
        "Revenue Q4",
        "FG Inventory (weeks)",
        "BI Income Q1",
        "BI Income Q2",
        "BI Income Q3",
        "BI Income Q4",
        "Operating Profit Q1",
        "Operating Profit Q2",
        "Operating Profit Q3",
        "Operating Profit Q4",
    ],
    "5. Executional Details": [
        "Part #",
        "3M Demand",
        "6M Demand",
        "Inventory On-Hand",
        "Inventory On-Order",
        "Reduced Lead Time",
        "Full Lead Time",
        "Type of Procurement Method",
        "Company Part Custom Defined Risk Score (1)",
        "Company Part Custom Defined Risk Score (2)",
        "Company Part Custom Defined Risk Score (3)",
        "Company Part Custom Defined Risk Score (4)",
        "Company Part Custom Defined Risk Score (5)",
    ],
    "6. Site List": [
        "Site Number",
        "Street Address 1",
        "Street Address 2",
        "City",
        "State/ Province",
        "Postal/ Zip Code",
        "Country",
        "Site Ownership",
        "Activity",
        "Recovery Time",
        "Alternate Site Number",
        "Alternate Site Bring Up Time",
        "Partner Name",
        "Subcontractor Name",
        "Site DUNS Number",
        "Site Emergency Contact- Name",
        "Site Emergency Contact- Email",
        "Site Emergency Contact- Work Phone",
    ],
    "7. Product - Site Map": [
        "Product Name",
        "Alt Site Qualified? Y/N",
        "Site Number",
        "Activity",
        "Recovery Time",
        "Revenue Split",
    ],
    "8. Part - Site Map": [
        "Partner Name",
        "Partner Part #",
        "Alt Site Qualified?",
        "Site Number",
        "Activity",
        "Recovery Time",
        "Alternate Site Number",
        "Alternate Site Bring Up Time",
    ],
    "9. Customer Contact Information": [
        "Name of Contact",
        "Contact Email Address",
        "Contact Phone Number",
        "Contact Title",
        "Resilinc User Type",
        "Receive EventWatch Emails?",
        "Receive EventWatch Impact Notifications?",
    ],
    "11. Site to Site Mapping": [
        "From Site Number",
        "To Site Number",
        "Partner Part #",
    ],
}

sheet_names = [
    "1. Partners",
    "2. Part sourcing",
    "3. BOM and Alt Parts",
    "4. Product",
    "5. Executional Details",
    "6. Site List",
    "7. Product - Site Map",
    "8. Part - Site Map",
    "9. Customer Contact Information",
    "11. Site to Site Mapping",
]
